/// Declare a typed translation tree generated by the optional codegen bridge.
///
/// Requires feature `codegen`. In build.rs, call
/// `bevy_fluent_codegen_bridge::build()` using its `build` feature. The bridge owns
/// the output layout; this facade forwards the runtime path hygienically, including
/// when the Cargo dependency is renamed. With Cargo resolver 2/3, generation stays
/// in the build-script dependency graph rather than the application runtime.
///
/// ```ignore
/// bevy_fluent_typed::translations!(pub mod texts);
/// ```
#[macro_export]
macro_rules! translations {
	($($tokens:tt)*) => {
		$crate::__codegen::translations!(runtime = $crate; $($tokens)*);
	};
}

/// Apply the selected engine's resource contract to a generated declaration.
/// Chosen in the runtime graph, never through the consumer's cfg or build.rs.
#[doc(hidden)]
#[cfg(feature = "bevy-0-19")]
#[macro_export]
macro_rules! __localized_resource {
	($declaration:item) => {
		#[derive($crate::bevy::prelude::Resource)]
		#[component(immutable)]
		$declaration
	};
}

/// Older Bevy backends have resources but no ECS-level resource immutability.
#[doc(hidden)]
#[cfg(not(feature = "bevy-0-19"))]
#[macro_export]
macro_rules! __localized_resource {
	($declaration:item) => {
		#[derive($crate::bevy::prelude::Resource)]
		$declaration
	};
}
